In [1]:
import pandas as pd
df=pd.read_csv('anova_IG.csv')
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
df

,D.Vaccine Protection Perception,D.Side Effect Confidence,D.Clinical Trial Confidence,D.Chip Belief,D.Mandatory Belief,D.Halal Doubt,D.Alternative Medicine Belief,B.View of vaccine,B.Vaccine Side Effects,C.Non_hesitant
0,4,4,4,4,4,4,3,0,1,1
1,4,4,4,4,2,4,4,2,1,0
2,3,3,3,4,3,4,3,0,0,1
3,4,3,3,4,3,3,4,0,1,1
4,2,2,2,4,2,3,2,2,1,0
5,3,2,2,4,2,2,3,0,1,0
6,4,4,4,4,3,4,4,0,0,1
7,4,4,4,0,4,0,0,0,1,1
8,2,2,2,3,2,2,3,2,1,0
9,4,4,4,4,4,4,4,0,0,1


In [2]:
import warnings
import numpy as np

# Suppress overflow warning
warnings.filterwarnings("ignore", category=RuntimeWarning)
np.seterr(over='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [3]:
df.dtypes

D.Vaccine Protection Perception    int64
D.Side Effect Confidence           int64
D.Clinical Trial Confidence        int64
D.Chip Belief                      int64
D.Mandatory Belief                 int64
D.Halal Doubt                      int64
D.Alternative Medicine Belief      int64
B.View of vaccine                  int64
B.Vaccine Side Effects             int64
C.Non_hesitant                     int64
dtype: object

In [4]:
df.shape

(554, 10)

In [5]:
# Convert integer to string: survived
df['C.Non_hesitant'] = df['C.Non_hesitant'].astype(str)
df['C.Non_hesitant'].describe()

count     554
unique      2
top         1
freq      321
Name: C.Non_hesitant, dtype: object

In [6]:
df['C.Non_hesitant'].value_counts()

C.Non_hesitant
1    321
0    233
Name: count, dtype: int64

In [7]:
target=df["C.Non_hesitant"]
features=df.drop('C.Non_hesitant',axis=1)

# SPLIT UNSCALED

In [8]:
# Split data into train and test sets

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split the dataset into training + development set and test set
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size = 0.2, random_state = 0)

# KNN UNSCALED

In [9]:
from sklearn.neighbors import KNeighborsClassifier
# Train the model using the entire training set with the best k
knn_best = KNeighborsClassifier(n_neighbors=9)
knn_best.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [10]:
# Predict the target for the test dataset
test_predict = knn_best.predict(x_test)
test_predict

array(['0', '0', '1', '1', '0', '1', '1', '1', '0', '0', '0', '0', '1',
       '1', '1', '0', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1',
       '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1', '0', '0',
       '1', '1', '1', '1', '1', '1', '0', '0', '0', '1', '1', '1', '1',
       '0', '0', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '1',
       '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0',
       '0', '1', '1', '1', '1', '1', '0', '0', '0', '1', '1', '1', '1',
       '0', '0', '1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '1',
       '1', '0', '1', '1', '1', '0', '0'], dtype=object)

In [11]:
# Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.8288288288288288


In [12]:
# Import scikit-learn metrics methods
from sklearn.metrics import classification_report, confusion_matrix

# Print confusion matrix
print(confusion_matrix(y_test, test_predict))

# Print precision, recall and F1 scores
print(classification_report(y_test, test_predict))

[[35 10]
 [ 9 57]]
              precision    recall  f1-score   support

           0       0.80      0.78      0.79        45
           1       0.85      0.86      0.86        66

    accuracy                           0.83       111
   macro avg       0.82      0.82      0.82       111
weighted avg       0.83      0.83      0.83       111



# DECISION TREE UNSCALED 

In [13]:
from sklearn.tree import DecisionTreeClassifier
# Train the model using the entire training set with the best depth
dtree_best = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
dtree_best.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [14]:
# Predict the target for the test dataset
test_predict = dtree_best.predict(x_test)

test_predict

array(['1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '0', '1',
       '1', '1', '0', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1',
       '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '1', '0', '0',
       '1', '1', '1', '1', '1', '1', '0', '0', '0', '1', '1', '1', '1',
       '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0',
       '0', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '1', '1',
       '1', '1', '1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '1',
       '1', '0', '1', '1', '0', '0', '0'], dtype=object)

In [15]:
# Evaluate the decision tree model on test set

# Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Compute the model accuracy on the test set: How often is the classifier correct?
accuracy = metrics.accuracy_score(y_test, test_predict)
print("Accuracy: ", accuracy)

Accuracy:  0.8378378378378378


In [16]:
# Import scikit-learn metrics methods
from sklearn.metrics import classification_report, confusion_matrix

# Print confusion matrix
print(confusion_matrix(y_test, test_predict))

# Print precision, recall and F1 scores
print(classification_report(y_test, test_predict))

[[32 13]
 [ 5 61]]
              precision    recall  f1-score   support

           0       0.86      0.71      0.78        45
           1       0.82      0.92      0.87        66

    accuracy                           0.84       111
   macro avg       0.84      0.82      0.83       111
weighted avg       0.84      0.84      0.83       111



# BAYES UNSCALED

Multinomial Naive Bayes

In [17]:
# Import the Multinomial Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
# Import function for k-fold cross validation
from sklearn.model_selection import cross_val_score

# Create a Multinomial Naive Bayes classifier with default parameters
mnb = MultinomialNB()

# Use 5-fold cross validation to perform training and validation on the training set
scores = cross_val_score(mnb, x_train, y_train, cv = 5, scoring = 'accuracy')

# Display the array containing accuracy from 10 folds or iterations
scores

array([0.7752809 , 0.75280899, 0.74157303, 0.71590909, 0.85227273])

In [18]:
# Print the mean accuracy score
print('Accuracy (Validation) =', scores.mean())

Accuracy (Validation) = 0.7675689479060266


In [19]:
# Running prediction
mnb.fit(x_train, y_train)

# Predict the target for the test dataset
test_predict = mnb.predict(x_test)

# Compute the model accuracy on the development set: How often is the classifier correct?
print("Accuracy (Test): ", metrics.accuracy_score(y_test, test_predict))

Accuracy (Test):  0.8108108108108109


In [20]:
# Import scikit-learn metrics methods
from sklearn.metrics import classification_report, confusion_matrix

# Print confusion matrix
print(confusion_matrix(y_test, test_predict))

# Print precision, recall and F1 scores
print(classification_report(y_test, test_predict))

[[36  9]
 [12 54]]
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        45
           1       0.86      0.82      0.84        66

    accuracy                           0.81       111
   macro avg       0.80      0.81      0.81       111
weighted avg       0.81      0.81      0.81       111



# NEURAL NETWORK UNSCALED

In [21]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

# Define the hidden layer sizes
hidden_layer_size = (5,10)

def train_and_evaluate(hidden_layer_size, x_train, y_train, x_test, y_test):
    # Initialize the MLPClassifier with the given hidden layer size
    mlp = MLPClassifier(hidden_layer_sizes=hidden_layer_size, max_iter=3000, random_state=42)
    # Train the model
    mlp.fit(x_train, y_train)
    # Make predictions
    test_predict = mlp.predict(x_test)
    # Evaluate the model
    accuracy = metrics.accuracy_score(y_test, test_predict)
    print(f'Accuracy (Test) for hidden layer size {hidden_layer_size}: {accuracy}')
    print(confusion_matrix(y_test, test_predict))
    print(classification_report(y_test, test_predict))


In [22]:
# Call the function with the actual data
train_and_evaluate(hidden_layer_size, x_train, y_train, x_test, y_test)

Accuracy (Test) for hidden layer size (5, 10): 0.8648648648648649
[[35 10]
 [ 5 61]]
              precision    recall  f1-score   support

           0       0.88      0.78      0.82        45
           1       0.86      0.92      0.89        66

    accuracy                           0.86       111
   macro avg       0.87      0.85      0.86       111
weighted avg       0.87      0.86      0.86       111



# SVM UNSCALED

linear

In [23]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

# Linear SVM
print("Evaluating Linear SVM")
model_linear = SVC(kernel='linear', C=0.1)
model_linear.fit(x_train, y_train)

# Predict and evaluate
y_pred_linear = model_linear.predict(x_test)
acc_linear = metrics.accuracy_score(y_test, y_pred_linear)
print(f"Accuracy (Test) for Linear SVM: {acc_linear}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_linear))
print("Classification Report:")
print(classification_report(y_test, y_pred_linear))
print("\n" + "="*60 + "\n")


Evaluating Linear SVM
Accuracy (Test) for Linear SVM: 0.8468468468468469
Confusion Matrix:
[[33 12]
 [ 5 61]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.73      0.80        45
           1       0.84      0.92      0.88        66

    accuracy                           0.85       111
   macro avg       0.85      0.83      0.84       111
weighted avg       0.85      0.85      0.84       111





In [24]:
# RBF SVM
print("Evaluating RBF SVM")
model_rbf = SVC(kernel='rbf', C=10, gamma='scale')
model_rbf.fit(x_train, y_train)

# Predict and evaluate
y_pred_rbf = model_rbf.predict(x_test)
acc_rbf = metrics.accuracy_score(y_test, y_pred_rbf)
print(f"Accuracy (Test) for RBF SVM: {acc_rbf}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rbf))
print("Classification Report:")
print(classification_report(y_test, y_pred_rbf))
print("\n" + "="*60 + "\n")


Evaluating RBF SVM
Accuracy (Test) for RBF SVM: 0.8378378378378378
Confusion Matrix:
[[34 11]
 [ 7 59]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        45
           1       0.84      0.89      0.87        66

    accuracy                           0.84       111
   macro avg       0.84      0.82      0.83       111
weighted avg       0.84      0.84      0.84       111



