In [1]:
import pandas as pd
df=pd.read_csv('anova_chi.csv')
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
df

,D.Vaccine Protection Perception,D.Side Effect Confidence,D.Clinical Trial Confidence,D.Chip Belief,D.Mandatory Belief,D.Halal Doubt,D.Alternative Medicine Belief,A.Monthly Income,A.Immunity Boosters,B.Family/Friend Side Effects,B.View of vaccine,A.Blog,A.Orang,A.Ethnicity,C.Non_hesitant
0,4,4,4,4,4,4,3,2,0,0,0,0,0,0,1
1,4,4,4,4,2,4,4,3,1,1,2,0,0,0,0
2,3,3,3,4,3,4,3,2,0,0,0,0,0,0,1
3,4,3,3,4,3,3,4,2,0,0,0,0,0,0,1
4,2,2,2,4,2,3,2,1,0,1,2,0,1,0,0
5,3,2,2,4,2,2,3,1,0,0,0,0,0,0,0
6,4,4,4,4,3,4,4,3,0,0,0,0,0,0,1
7,4,4,4,0,4,0,0,2,0,1,0,0,0,0,1
8,2,2,2,3,2,2,3,1,1,1,2,0,0,0,0
9,4,4,4,4,4,4,4,2,0,0,0,0,0,1,1


In [2]:
import warnings
import numpy as np

# Suppress overflow warning
warnings.filterwarnings("ignore", category=RuntimeWarning)
np.seterr(over='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [3]:
target=df["C.Non_hesitant"]
features=df.drop('C.Non_hesitant',axis=1)

In [4]:
# Split data into train and test sets

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split the dataset into training + development set and test set
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size = 0.2, random_state = 0)

# RANDOM FOREST

In [5]:
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Random Forest Bagging
model_bagging_rf = BaggingClassifier(estimator=RandomForestClassifier(), n_estimators=10, random_state=7)

# Cross-validation
print("Model: Random Forest")
scores_rf = cross_val_score(model_bagging_rf, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold: ", scores_rf)
print("Mean Accuracy (Validation):", scores_rf.mean())
print("-" * 50)

# Test set evaluation
model_bagging_rf.fit(x_train, y_train)
test_predict_rf = model_bagging_rf.predict(x_test)
print("Random Forest Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_rf))
print("=" * 50)

Model: Random Forest
Accuracy scores for each fold:  [0.84269663 0.88764045 0.82022472 0.82954545 0.86363636]
Mean Accuracy (Validation): 0.8487487231869254
--------------------------------------------------
Random Forest Bagging - Accuracy (Test): 0.8738738738738738


# BAGGING

NN

In [6]:
# Import necessary libraries
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Neural Network with one hidden layer of 5 neurons
model_bagging_nn = BaggingClassifier(
    estimator=MLPClassifier(hidden_layer_sizes=(5,10), max_iter=200, random_state=7), 
    n_estimators=10, 
    random_state=7
)

# Cross-validation
print("Model: Neural Network (5 neurons in the hidden layer)")
scores_nn = cross_val_score(model_bagging_nn, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold: ", scores_nn)
print("Mean Accuracy (Validation):", scores_nn.mean())
print("-" * 50)

# Test set evaluation
model_bagging_nn.fit(x_train, y_train)
test_predict_nn = model_bagging_nn.predict(x_test)
print("Neural Network Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_nn))
print("=" * 50)


Model: Neural Network (5 neurons in the hidden layer)


/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/pyth

Accuracy scores for each fold:  [0.82022472 0.74157303 0.78651685 0.76136364 0.79545455]
Mean Accuracy (Validation): 0.781026557711951
--------------------------------------------------


/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/pyth

Neural Network Bagging - Accuracy (Test): 0.8468468468468469


/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [7]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Linear SVM Bagging (with probability=True for flexibility)
model_bagging_linear_svm = BaggingClassifier(
    estimator=SVC(kernel='linear', C=0.1, probability=True),
    n_estimators=10,
    random_state=7
)

# Cross-validation
print("Model: Linear SVM (C=0.1)")
scores_linear_svm = cross_val_score(model_bagging_linear_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:", scores_linear_svm)
print("Mean Accuracy (Validation):", scores_linear_svm.mean())
print("-" * 50)

# Test set evaluation
model_bagging_linear_svm.fit(x_train, y_train)
test_predict_linear_svm = model_bagging_linear_svm.predict(x_test)
print("Linear SVM Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_linear_svm))
print("=" * 50)


Model: Linear SVM (C=0.1)
Accuracy scores for each fold: [0.86516854 0.88764045 0.84269663 0.81818182 0.86363636]
Mean Accuracy (Validation): 0.855464759959142
--------------------------------------------------
Linear SVM Bagging - Accuracy (Test): 0.8738738738738738


In [8]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Polynomial SVM Bagging (with probability=True for flexibility)
model_bagging_poly_svm = BaggingClassifier(
    estimator=SVC(kernel='poly', C=1, degree=3, gamma='scale', probability=True),
    n_estimators=10,
    random_state=7
)

# Cross-validation
print("Model: Polynomial SVM (C=1, degree=3)")
scores_poly_svm = cross_val_score(model_bagging_poly_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:", scores_poly_svm)
print("Mean Accuracy (Validation):", scores_poly_svm.mean())
print("-" * 50)

# Fit and Test evaluation
model_bagging_poly_svm.fit(x_train, y_train)
test_predict_poly_svm = model_bagging_poly_svm.predict(x_test)
print("Polynomial SVM Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_poly_svm))
print("=" * 50)


Model: Polynomial SVM (C=1, degree=3)
Accuracy scores for each fold: [0.86516854 0.87640449 0.84269663 0.81818182 0.86363636]
Mean Accuracy (Validation): 0.8532175689479061
--------------------------------------------------
Polynomial SVM Bagging - Accuracy (Test): 0.8828828828828829


In [9]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# RBF SVM Bagging (with probability=True for flexibility)
model_bagging_rbf_svm = BaggingClassifier(
    estimator=SVC(kernel='rbf', C=10, gamma='scale', probability=True),
    n_estimators=10,
    random_state=7
)

# Cross-validation
print("Model: RBF SVM (C=10, gamma='scale')")
scores_rbf_svm = cross_val_score(model_bagging_rbf_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:", scores_rbf_svm)
print("Mean Accuracy (Validation):", scores_rbf_svm.mean())
print("-" * 50)

# Test set evaluation
model_bagging_rbf_svm.fit(x_train, y_train)
test_predict_rbf_svm = model_bagging_rbf_svm.predict(x_test)
print("RBF SVM Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_rbf_svm))
print("=" * 50)


Model: RBF SVM (C=10, gamma='scale')
Accuracy scores for each fold: [0.87640449 0.85393258 0.85393258 0.81818182 0.84090909]
Mean Accuracy (Validation): 0.8486721144024516
--------------------------------------------------
RBF SVM Bagging - Accuracy (Test): 0.8738738738738738


# Boosting

In [10]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Define the Gradient Boosting classifier
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Cross-validation
cv_scores = cross_val_score(gbc, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold (CV): ", cv_scores)
print("Mean Accuracy (Validation): {:.4f}".format(cv_scores.mean()))
print("-" * 50)

# Fit the model on the full training data
gbc.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred = gbc.predict(x_test)
accuracy = accuracy_score(y_test, y_test_pred)

# Print evaluation metrics
print(f'Accuracy (Test): {accuracy:.4f}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred))
print('Classification Report:')
print(classification_report(y_test, y_test_pred))
print("=" * 50)


Accuracy scores for each fold (CV):  [0.82022472 0.84269663 0.78651685 0.81818182 0.86363636]
Mean Accuracy (Validation): 0.8263
--------------------------------------------------
Accuracy (Test): 0.8739
Confusion Matrix:
[[37  8]
 [ 6 60]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.82      0.84        45
           1       0.88      0.91      0.90        66

    accuracy                           0.87       111
   macro avg       0.87      0.87      0.87       111
weighted avg       0.87      0.87      0.87       111



In [11]:
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Define the XGBoost classifier
xgb_clf = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Cross-validation
cv_scores = cross_val_score(xgb_clf, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold (CV): ", cv_scores)
print("Mean Accuracy (Validation): {:.4f}".format(cv_scores.mean()))
print("-" * 50)

# Fit the model on the full training data
xgb_clf.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred = xgb_clf.predict(x_test)
accuracy = accuracy_score(y_test, y_test_pred)

# Print evaluation metrics
print(f'Accuracy (Test): {accuracy:.4f}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred))
print('Classification Report:')
print(classification_report(y_test, y_test_pred))
print("=" * 50)


Accuracy scores for each fold (CV):  [0.83146067 0.85393258 0.83146067 0.80681818 0.86363636]
Mean Accuracy (Validation): 0.8375
--------------------------------------------------
Accuracy (Test): 0.8649
Confusion Matrix:
[[37  8]
 [ 7 59]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.82      0.83        45
           1       0.88      0.89      0.89        66

    accuracy                           0.86       111
   macro avg       0.86      0.86      0.86       111
weighted avg       0.86      0.86      0.86       111



# ADABOOSTING

rbf

In [12]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the RBF SVM base estimator with updated parameters
rbf_svm = SVC(kernel='rbf', probability=True, C=10, gamma='scale', random_state=7)

# AdaBoost with RBF SVM
ada_rbf_svm = AdaBoostClassifier(estimator=rbf_svm, n_estimators=10, random_state=7)

# Cross-validation
cv_scores_rbf_svm = cross_val_score(ada_rbf_svm, x_train, y_train, cv=5, scoring='accuracy')
print("RBF SVM - Accuracy scores for each fold (CV): ", cv_scores_rbf_svm)
print("RBF SVM - Mean Accuracy (Validation): {:.4f}".format(cv_scores_rbf_svm.mean()))
print("-" * 50)

# Fit the model on the full training data
ada_rbf_svm.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred_rbf_svm = ada_rbf_svm.predict(x_test)
accuracy_rbf_svm = accuracy_score(y_test, y_test_pred_rbf_svm)

# Print evaluation metrics
print(f'RBF SVM - Accuracy (Test): {accuracy_rbf_svm:.4f}')
print('RBF SVM - Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred_rbf_svm))
print('RBF SVM - Classification Report:')
print(classification_report(y_test, y_test_pred_rbf_svm))
print("=" * 50)

RBF SVM - Accuracy scores for each fold (CV):  [0.82022472 0.79775281 0.79775281 0.77272727 0.82954545]
RBF SVM - Mean Accuracy (Validation): 0.8036
--------------------------------------------------
RBF SVM - Accuracy (Test): 0.8288
RBF SVM - Confusion Matrix:
[[41  4]
 [15 51]]
RBF SVM - Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.91      0.81        45
           1       0.93      0.77      0.84        66

    accuracy                           0.83       111
   macro avg       0.83      0.84      0.83       111
weighted avg       0.85      0.83      0.83       111



In [13]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the Linear SVM base estimator with updated parameters
linear_svm = SVC(kernel='linear', probability=True, C=0.1, random_state=7)

# AdaBoost with Linear SVM
ada_linear_svm = AdaBoostClassifier(estimator=linear_svm, n_estimators=10, random_state=7)

# Cross-validation
cv_scores_linear_svm = cross_val_score(ada_linear_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Linear SVM - Accuracy scores for each fold (CV): ", cv_scores_linear_svm)
print("Linear SVM - Mean Accuracy (Validation): {:.4f}".format(cv_scores_linear_svm.mean()))
print("-" * 50)

# Fit the model on the full training data
ada_linear_svm.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred_linear_svm = ada_linear_svm.predict(x_test)
accuracy_linear_svm = accuracy_score(y_test, y_test_pred_linear_svm)

# Print evaluation metrics
print(f'Linear SVM - Accuracy (Test): {accuracy_linear_svm:.4f}')
print('Linear SVM - Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred_linear_svm))
print('Linear SVM - Classification Report:')
print(classification_report(y_test, y_test_pred_linear_svm))
print("=" * 50)


Linear SVM - Accuracy scores for each fold (CV):  [0.64044944 0.66292135 0.58426966 0.71590909 0.625     ]
Linear SVM - Mean Accuracy (Validation): 0.6457
--------------------------------------------------
Linear SVM - Accuracy (Test): 0.6667
Linear SVM - Confusion Matrix:
[[41  4]
 [33 33]]
Linear SVM - Classification Report:
              precision    recall  f1-score   support

           0       0.55      0.91      0.69        45
           1       0.89      0.50      0.64        66

    accuracy                           0.67       111
   macro avg       0.72      0.71      0.66       111
weighted avg       0.75      0.67      0.66       111



In [14]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the Polynomial SVM base estimator
poly_svm = SVC(kernel='poly', C=1, degree=3, gamma='scale', probability=True, random_state=7)

# AdaBoost with Polynomial SVM
ada_poly_svm = AdaBoostClassifier(estimator=poly_svm, n_estimators=10, random_state=7)

# Cross-validation
cv_scores_poly_svm = cross_val_score(ada_poly_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Polynomial SVM - Accuracy scores for each fold (CV): ", cv_scores_poly_svm)
print("Polynomial SVM - Mean Accuracy (Validation): {:.4f}".format(cv_scores_poly_svm.mean()))
print("-" * 50)

# Fit the model on the full training data
ada_poly_svm.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred_poly_svm = ada_poly_svm.predict(x_test)
accuracy_poly_svm = accuracy_score(y_test, y_test_pred_poly_svm)

# Print evaluation metrics
print(f'Polynomial SVM - Accuracy (Test): {accuracy_poly_svm:.4f}')
print('Polynomial SVM - Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred_poly_svm))
print('Polynomial SVM - Classification Report:')
print(classification_report(y_test, y_test_pred_poly_svm))
print("=" * 50)


Polynomial SVM - Accuracy scores for each fold (CV):  [0.80898876 0.82022472 0.84269663 0.76136364 0.81818182]
Polynomial SVM - Mean Accuracy (Validation): 0.8103
--------------------------------------------------
Polynomial SVM - Accuracy (Test): 0.8198
Polynomial SVM - Confusion Matrix:
[[41  4]
 [16 50]]
Polynomial SVM - Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.91      0.80        45
           1       0.93      0.76      0.83        66

    accuracy                           0.82       111
   macro avg       0.82      0.83      0.82       111
weighted avg       0.84      0.82      0.82       111



In [15]:
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# KNN (k=23) - Bagging only
model_bagging_knn = BaggingClassifier(
    estimator=KNeighborsClassifier(n_neighbors=9),
    n_estimators=10,
    random_state=7
)
print("Model: KNN (k=23) - Bagging")
scores = cross_val_score(model_bagging_knn, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_bagging_knn.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_bagging_knn.predict(x_test)))
print("=" * 50)

# Decision Tree (depth=4) - Bagging
model_bagging_dt = BaggingClassifier(
    estimator=DecisionTreeClassifier(max_depth=3, random_state=7),
    n_estimators=10,
    random_state=7
)
print("Model: Decision Tree (depth=4) - Bagging")
scores = cross_val_score(model_bagging_dt, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_bagging_dt.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_bagging_dt.predict(x_test)))
print("=" * 50)

# Decision Tree (depth=4) - AdaBoost
model_adaboost_dt = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=3, random_state=7),
    n_estimators=50,
    random_state=7
)
print("Model: Decision Tree (depth=3) - AdaBoost")
scores = cross_val_score(model_adaboost_dt, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_adaboost_dt.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_adaboost_dt.predict(x_test)))
print("=" * 50)

# MultinomialNB - Bagging only
model_bagging_mnb = BaggingClassifier(
    estimator=MultinomialNB(),
    n_estimators=10,
    random_state=7
)
print("Model: MultinomialNB - Bagging")
scores = cross_val_score(model_bagging_mnb, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_bagging_mnb.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_bagging_mnb.predict(x_test)))
print("=" * 50)


Model: KNN (k=23) - Bagging
Validation Accuracy: 0.8351889683350358
Test Accuracy: 0.8828828828828829
Model: Decision Tree (depth=4) - Bagging
Validation Accuracy: 0.8533197139938713
Test Accuracy: 0.8648648648648649
Model: Decision Tree (depth=3) - AdaBoost
Validation Accuracy: 0.8306945863125639
Test Accuracy: 0.8378378378378378
Model: MultinomialNB - Bagging
Validation Accuracy: 0.7584780388151174
Test Accuracy: 0.7837837837837838
